import type { Ticket } from '@/shared/types/ticket.types';

export const SEED_TICKETS: Ticket[] = [
  {
    id: 'TK-1042',
    subject: 'Truck breakdown on I-35 near Waco, TX — load undelivered',
    priority: 'critical',
    status: 'open',
    agentId: 'agent-001',
    agentName: 'Marcus T.',
    createdAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    description: 'Driver reports engine failure at mile marker 262. Load is temperature-sensitive. Requires immediate dispatch of relief vehicle.',
    location: 'Waco, TX',
  },
  {
    id: 'TK-1041',
    subject: 'Double billing dispute — client Hartwell Grocers, FL',
    priority: 'high',
    status: 'in_progress',
    agentId: 'agent-002',
    agentName: 'Priya S.',
    createdAt: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
    description: 'Client was charged twice for delivery #RD-8821. Finance team needs to process refund and send corrected invoice.',
    location: 'Orlando, FL',
  },
  {
    id: 'TK-1040',
    subject: 'Missed delivery window — SLA breach, Apex Pharma, NJ',
    priority: 'critical',
    status: 'open',
    agentId: 'agent-003',
    agentName: 'Jordan K.',
    createdAt: new Date(Date.now() - 32 * 60 * 1000).toISOString(),
    description: 'Pharmaceutical delivery arrived 4 hours late. Client has activated SLA penalty clause. Escalate to operations director.',
    location: 'Newark, NJ',
  },
  {
    id: 'TK-1039',
    subject: 'Damaged freight — pallet 7 of 12, Sunbelt Foods, GA',
    priority: 'high',
    status: 'open',
    agentId: 'agent-004',
    agentName: 'Aisha R.',
    createdAt: new Date(Date.now() - 47 * 60 * 1000).toISOString(),
    description: 'Receiving team reports forklift damage on arrival. Photos uploaded. Insurance claim to be initiated.',
    location: 'Atlanta, GA',
  },
  {
    id: 'TK-1038',
    subject: 'Wrong address on manifest — shipment diverted, AZ',
    priority: 'high',
    status: 'in_progress',
    agentId: 'agent-005',
    agentName: 'Devon L.',
    createdAt: new Date(Date.now() - 62 * 60 * 1000).toISOString(),
    description: 'Driver followed manifest which had incorrect ZIP. Shipment is currently 80 miles off route. Coordinating with dispatch.',
    location: 'Phoenix, AZ',
  },
  {
    id: 'TK-1037',
    subject: 'GPS tracker offline — Unit RD-447, route unknown',
    priority: 'normal',
    status: 'open',
    agentId: 'agent-001',
    agentName: 'Marcus T.',
    createdAt: new Date(Date.now() - 75 * 60 * 1000).toISOString(),
    description: 'Telematics unit stopped transmitting at 09:14 CST. Driver is reachable by phone. IT to investigate device fault.',
    location: 'Kansas City, MO',
  },
  {
    id: 'TK-1036',
    subject: 'Fuel card declined — driver stranded, Amarillo TX',
    priority: 'critical',
    status: 'open',
    agentId: 'agent-006',
    agentName: 'Camille W.',
    createdAt: new Date(Date.now() - 88 * 60 * 1000).toISOString(),
    description: 'Card block triggered by fraud detection. Driver unable to refuel. Accounts team to whitelist and issue emergency fuel code.',
    location: 'Amarillo, TX',
  },
  {
    id: 'TK-1035',
    subject: 'Driver hours violation — ELD flagged, compliance risk',
    priority: 'high',
    status: 'in_progress',
    agentId: 'agent-007',
    agentName: 'Ravi P.',
    createdAt: new Date(Date.now() - 100 * 60 * 1000).toISOString(),
    description: 'ELD logged 11h 42m driving. FMCSA limit is 11h. Compliance officer reviewing log edits. Driver placed off-duty.',
    location: 'Memphis, TN',
  },
  {
    id: 'TK-1034',
    subject: 'Missing proof of delivery — client disputing receipt, CO',
    priority: 'normal',
    status: 'open',
    agentId: 'agent-008',
    agentName: 'Nadia O.',
    createdAt: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    description: 'Client claims delivery never occurred. Driver has photo POD but it was not uploaded to the portal. Pending retrieval.',
    location: 'Denver, CO',
  },
  {
    id: 'TK-1033',
    subject: 'Refrigeration unit failure — reefer trailer RD-T291',
    priority: 'critical',
    status: 'open',
    agentId: 'agent-009',
    agentName: 'Tyler B.',
    createdAt: new Date(Date.now() - 140 * 60 * 1000).toISOString(),
    description: 'Temperature alarm triggered at 28°F vs required 34–36°F range. Load is 8,000 lbs of frozen seafood. Maintenance dispatched.',
    location: 'Houston, TX',
  },
  {
    id: 'TK-1032',
    subject: 'Overweight load citation — weigh station, I-80 NE',
    priority: 'high',
    status: 'closed',
    agentId: 'agent-010',
    agentName: 'Simone F.',
    createdAt: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
    description: 'Load exceeded 80,000 lbs GVW. $1,200 fine issued. DOT permit was not obtained. Operations reviewing loader procedures.',
    location: 'Omaha, NE',
  },
  {
    id: 'TK-1031',
    subject: 'Customs hold — cross-border shipment, Laredo TX',
    priority: 'high',
    status: 'in_progress',
    agentId: 'agent-002',
    agentName: 'Priya S.',
    createdAt: new Date(Date.now() - 200 * 60 * 1000).toISOString(),
    description: 'CBP flagged manifest discrepancy on commodity description. Broker engaged. Estimated 6-hour delay.',
    location: 'Laredo, TX',
  },
  {
    id: 'TK-1030',
    subject: 'Traffic accident — no injuries, load intact, I-20 LA',
    priority: 'normal',
    status: 'in_progress',
    agentId: 'agent-003',
    agentName: 'Jordan K.',
    createdAt: new Date(Date.now() - 230 * 60 * 1000).toISOString(),
    description: 'Minor collision. Driver uninjured. Police report filed. Cargo secured. Insurance notified. ETA delayed by 3 hours.',
    location: 'Shreveport, LA',
  },
  {
    id: 'TK-1029',
    subject: 'Client escalation — repeated late deliveries, Seattle WA',
    priority: 'high',
    status: 'open',
    agentId: 'agent-004',
    agentName: 'Aisha R.',
    createdAt: new Date(Date.now() - 250 * 60 * 1000).toISOString(),
    description: 'Cascadia Retail Group has escalated to VP level. Third late delivery this month. Account at risk of churn.',
    location: 'Seattle, WA',
  },
  {
    id: 'TK-1028',
    subject: 'Dock scheduling conflict — warehouse turned away truck',
    priority: 'normal',
    status: 'closed',
    agentId: 'agent-005',
    agentName: 'Devon L.',
    createdAt: new Date(Date.now() - 300 * 60 * 1000).toISOString(),
    description: 'Warehouse had no appointment logged for 14:00 slot. Appointment was made via email, not portal. Rescheduled to next day.',
    location: 'Indianapolis, IN',
  },
  {
    id: 'TK-1027',
    subject: 'Driver no-show — route RD-2210 uncovered, Chicago IL',
    priority: 'critical',
    status: 'open',
    agentId: 'agent-006',
    agentName: 'Camille W.',
    createdAt: new Date(Date.now() - 320 * 60 * 1000).toISOString(),
    description: 'Assigned driver failed to report. Backup driver sourced but pickup delayed by 90 minutes. Shipper notified.',
    location: 'Chicago, IL',
  },
  {
    id: 'TK-1026',
    subject: 'Load rejection — packaging non-compliant, Detroit MI',
    priority: 'normal',
    status: 'closed',
    agentId: 'agent-007',
    agentName: 'Ravi P.',
    createdAt: new Date(Date.now() - 360 * 60 * 1000).toISOString(),
    description: 'Receiver rejected load citing non-ISPM 15 compliant wooden pallets. Load returned to shipper for repackaging.',
    location: 'Detroit, MI',
  },
  {
    id: 'TK-1025',
    subject: 'Invoice dispute — mileage overcharge, Dallas TX',
    priority: 'normal',
    status: 'in_progress',
    agentId: 'agent-008',
    agentName: 'Nadia O.',
    createdAt: new Date(Date.now() - 400 * 60 * 1000).toISOString(),
    description: 'Client disputes 47-mile discrepancy on invoice RD-INV-9032. Pulling GPS logs to verify actual route taken.',
    location: 'Dallas, TX',
  },
  {
    id: 'TK-1024',
    subject: 'Stolen cargo report — flatbed trailer RD-F88, Nashville TN',
    priority: 'critical',
    status: 'in_progress',
    agentId: 'agent-009',
    agentName: 'Tyler B.',
    createdAt: new Date(Date.now() - 420 * 60 * 1000).toISOString(),
    description: 'Driver reported trailer theft at truck stop overnight. Police contacted. Cargo value est. $240K. Insurance escalated.',
    location: 'Nashville, TN',
  },
  {
    id: 'TK-1023',
    subject: 'System sync error — dispatch portal showing wrong status',
    priority: 'normal',
    status: 'open',
    agentId: 'agent-010',
    agentName: 'Simone F.',
    createdAt: new Date(Date.now() - 480 * 60 * 1000).toISOString(),
    description: 'Portal shows 6 deliveries as "Pending" that were completed 2 hours ago. IT team investigating TMS sync lag.',
    location: 'Dallas, TX (HQ)',
  },
];
